ARDUINO_LIBRARIES := DHTesp
DISABLE_NETWORK := 1
HWCONFIG = spiffs

# Empty SPIFFS partition please
SPIFF_FILES :=

COMPONENT_CXXFLAGS += -DENABLE_FLASHSTRING_IMAGE=1

SPI_MODE = dio
SPI_SIZE        ?= 4M
HWCONFIG := spiffs
